# Generated by Django 2.0.6 on 2018-11-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BearLights', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
